name: e_invoice_generator
description: the package generates Qr code compatible with Electronic Invoice in KSA
version: 0.0.2
homepage: https://github.com/F-BONAPARTA/e-invoice-generator

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  
flutter:
